### PR TITLE
Add option to not salt cellular lookup

### PR DESCRIPTION
**Pull request by Astrashh**
# Pull Request

## Licensing

- [x] I am the original author of this code, and I am willing to release it
  under [GPLv3](https://www.gnu.org/licenses/gpl-3.0.en.html).
- [ ] I am not the original author of this code, but it is in public domain or
  released under [GPLv3](https://www.gnu.org/licenses/gpl-3.0.en.html) or a
  compatible license.
    

## Goal of the PR

Allows lookup samplers to not be affected by the cellular sampler's salt

## Affects of the PR

Only affects behavior if salting is explicitly turned off by setting `salt-lookup` to `false`

#### Types of changes

- [ ] Bug Fix 
- [ ] Build system 
- [ ] Documentation 
- [x] New Feature 
- [ ] Performance 
- [ ] Refactoring 
- [ ] Repository 
- [ ] Revert 
- [ ] Style 
- [ ] Tests 
- [ ] Translation 

#### Compatiblity

- [ ] Breaking
  change 
- [x] Non-Breaking change.
    

#### Contribution Guidelines.

- [x] I have read
  the [`CONTRIBUTING.md`](https://github.com/PolyhedralDev/Terra/blob/master/CONTRIBUTING.md)
  document in the root of the git repository.
- [x] My code follows the code style for this
  project. 

#### Documentation

- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

#### Testing

- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by duplexsystem** [comment]
I think it would be better to instead have an option for lookup salt where the default is the existing salt

**Comment by Astrashh** [comment]
the lookup can be independently salted like any other sampler, eg:
```yaml
type: CELLULAR
return: NoiseLookup
salt: 3
salt-lookup: true # default
lookup:
  type: OPEN_SIMPLEX_2 # Is actually salted as 3 + 6
  salt: 6
```
  
```yaml
type: CELLULAR
return: NoiseLookup
salt: 3
salt-lookup: false
lookup:
  type: OPEN_SIMPLEX_2 # Is salted as 6
  salt: 6
```

**Comment by duplexsystem** [comment]
hmm ok

**Review by duplexsystem — APPROVED** [review]

**Comment by duplexsystem** [comment]
@dfsek are you against merging this?

**Review by dfsek — APPROVED** [review]

**Pull request merged**
