### PR TITLE
Fix fabric development environment launch

### PR DESCRIPTION
**Pull request by ishland**
# Pull Request

## Brief description.
This PR fixes a crash when using Terra in the workspace of other mods. 
https://paste.ubuntu.com/p/gZxVn4vh3p/

## Licensing

- [x] I am the original author of this code, and I am willing to release it under [GPLv3](https://www.gnu.org/licenses/gpl-3.0.en.html).
- [ ] I am not the original author of this code, but it is in public domain or released
  under [GPLv3](https://www.gnu.org/licenses/gpl-3.0.en.html) or a compatible license.
    

#### Types of changes

- [x] Bug Fix 
- [ ] Build system 
- [ ] Documentation 
- [ ] New Feature 
- [ ] Performance 
- [ ] Refactoring 
- [ ] Repository 
- [ ] Revert 
- [ ] Style 
- [ ] Tests 
- [ ] Translation 

#### Compatiblity

- [ ] Breaking change 
- [x] Non-Breaking change.
    

#### Contribution Guidelines.

- [x] I have read the [`CONTRIBUTING.md`](https://github.com/PolyhedralDev/Terra/blob/master/CONTRIBUTING.md) document in the root of the
  git repository.
- [x] My code follows the code style for this
  project. 

#### Documentation

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

#### Testing

- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by solonovamax** [comment]
What's the point of copying it to a temp location?

**Comment by ishland** [comment]
> What's the point of copying it to a temp location?

The jar file is on a [jimfs](https://github.com/google/jimfs) after fabric-loader remapped terra and added it into classpath. So the `URI` cannot be converted to a `File` directly without copying it to another location.

**Review by dfsek — CHANGES_REQUESTED** [review]
Don't do this on every platform. Do a Fabric override, and have it only create a copy when it is in a development environment.

**Review by solonovamax — APPROVED** [review]
Seems fine to me

**Review by dfsek — APPROVED** [review]

**Pull request merged**
