### PR TITLE
Port to Folia

### LINKED ISSUE #397: [Feature] Folia port
### Pre-Request Checklist

- [x] I have checked that I am on the latest version of Terra.
- [x] I have searched github for similar features requests, including closed
  ones, and found none.
- [x] I believe this is within the scope of Terra.
- [x] This feature request is for *all* of Terra, and isn't something that
  should be implemented by a pack or addon.

## Feature Description

Terra should support Folia.

### What Problem Does This Solve?

Terra not running on Folia servers.

### A Solution You'd Like

Terra being ported to Folia.

### Alternative Solutions

Terra being ported to Folia.

### PR DESCRIPTION
**Pull request by pontaoski**
# Pull Request

## Brief description.

This adds Folia compatibility.

### What Issues Does This Fix?

Fix #397 

## Licensing

- [x] I am the original author of this code, and I am willing to release it
  under [GPLv3](https://www.gnu.org/licenses/gpl-3.0.en.html).
- [ ] I am not the original author of this code, but it is in public domain or
  released under [GPLv3](https://www.gnu.org/licenses/gpl-3.0.en.html) or a
  compatible license.
    

## Goal of the PR

- [x] Port to Folia

#### Types of changes

- [ ] Bug Fix 
- [x] Build system 
- [ ] Documentation 
- [x] New Feature 
- [ ] Performance 
- [x] Refactoring 
- [ ] Repository 
- [ ] Revert 
- [ ] Style 
- [ ] Tests 
- [ ] Translation 

#### Compatiblity

- [ ] Breaking
  change 
- [x] Non-Breaking change.
    

#### Contribution Guidelines.

- [x] I have read
  the [`CONTRIBUTING.md`](https://github.com/PolyhedralDev/Terra/blob/master/CONTRIBUTING.md)
  document in the root of the git repository.
- [x] My code follows the code style for this
  project.

### CODE REVIEW

**Comment by pontaoski** [comment]
grafik
seems to be working? :3

**Comment by solonovamax** [comment]
should the folia port be a separate submodule/platform?

and, why is the nms not being shaded?

**Comment by pontaoski** [comment]
folia is 99% the same code, so the usual way to port is to just switch the API package to folia and guard folia APIs behind version checks

also oops that was failing to build locally so i commented it out

**Comment by solonovamax** [comment]
nvm, run-paper already has folia support. run-paper should be updated to the latest version, `1.1.0`

**Comment by solonovamax** [comment]
we should attempt to have 1.19_r1 shaded again

**Comment by solonovamax** [comment]
also, idk about setting the folia dep to 1.20. that means that we could accidentally introduce changes that would prevent it from running on 1.18 bukkit.

**Comment by pontaoski** [comment]
folia doesn't come in a 1.18 API flavour

**Comment by solonovamax** [comment]
yes I know. which is another reason for having both a folia and a bukkit platform.

**Comment by justaureus** [comment]
> also, idk about setting the folia dep to 1.20. that means that we could accidentally introduce changes that would prevent it from running on 1.18 bukkit.

We don't support 1.18 bukkit anymore, only 1.19/1.20.

**Comment by solonovamax** [comment]
> We don't support 1.18 bukkit anymore, only 1.19/1.20.

ah, I see

however, it'd still (possibly) break on 1.19

**Comment by duplexsystem** [comment]
Superseded by #417

**Pull request closed without merging**
