### PR TITLE
Replace Math with FastMath for improved performance.

### PR DESCRIPTION
**Pull request by budgidiere**
FastMath is a drop in replacement for the native Java math class with improved performance and fall backs to the native Java math class if necessary.

https://commons.apache.org/proper/commons-math/javadocs/api-3.3/org/apache/commons/math3/util/FastMath.html

This requires further testing and might cause chunk borders due to FastMath giving slightly different results than the native Java math class.

I also added .idea/Terra.iml to the .gitignore

### CODE REVIEW

**Comment by dfsek** [comment]
This probably won't do all too much, as a vast majority of the math is handled by Parsii. We've already forked Parsii to make some changes, so I'll probably switch our fork over to FastMath as well.

This looks good tho, will accept after I do a bit of testing.

**Comment by solonovamax** [comment]
I was working on a fork of parsii with some changes to the math (+ was going to add sigmoid), so I could make a pr (eventually™) for that and you could add that

**Comment by solonovamax** [comment]
Also, I was like 95% sure that all iml files were already ignored, but I was still having issues with Terra.iml not going away.

**Comment by dfsek** [comment]
I've already switched our parsii fork over to FastMath

**Review by dfsek — APPROVED** [review]

**Pull request merged**
