### PR TITLE
Remove redundant carver code

### PR DESCRIPTION
**Pull request by Nathat23**

### CODE REVIEW

**Comment by dfsek** [comment]
That code is not redundant... It ensures that adjacent chunks are carved properly.

Test your PRs before opening next time ;)

**Comment by Nathat23** [comment]
Could you maybe explain how?

**Comment by dfsek** [comment]
Carving is chunkified, so it handles all chunks within a certain radius. That's why the cache is there. Take a look at the code, it's pretty straightforward.

**Comment by Nathat23** [comment]
Ah I was under the impression that carvers were used for rivers, but this doesn't seem to be the case.

**Pull request closed without merging**
